#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := keypad.cpp sound.cpp lock.cpp motor.cpp movement.cpp PWM_signal.cpp system.cpp servo.cpp 

# header files in this project
HEADERS := touchless_safe.hpp keypad.hpp sound.hpp lock.hpp motor.hpp movement.hpp PWM_signal.hpp system.hpp servo.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due

