#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := keypad.cpp sound.cpp sound_lock.cpp password.cpp  pwm.cpp motor_g9.cpp movement.cpp lock.cpp profile.cpp

# header files in this project
HEADERS := touchless_safe.hpp keypad.hpp sound.hpp sound_lock.hpp password.hpp pwm.hpp motor_g9.hpp movement.hpp lock.hpp profile.hpp

# other places to look for files for this project
SEARCH  := 

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due

